[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Scheduled Netlify Function: ebay-orders-sync
# Runs every 5 minutes to ingest eBay orders and decrement EBAY stock on parent products
[functions."ebay-orders-sync"]
  schedule = "*/5 * * * *"

# Scheduled Netlify Function: marketplaces-reconcile-stock
# Runs every 10 minutes to reconcile EBAY depot quantities to eBay offers (keeps sync alive even if app is closed)
[functions."marketplaces-reconcile-stock"]
  schedule = "*/10 * * * *"
