export interface ProductWithStock {
  id: string;
  name: string;
  sku: string;
  purchase_price_with_fees: number | null;
  stock: number;
  description: string | null;
  created_at: string | null;
  updated_at: string | null;
  weight_grams: number;
  ean: string | null;
  retail_price: number | null;
  pro_price: number | null;
  images: string[] | null;
  width_cm: number | null;
  height_cm: number | null;
  depth_cm: number | null;
  shipping_box_id: string | null;
  stock_alert: number | null;
  category_id: string | null;
  variants: any;
  location: string | null;
  purchase_price_2: number | null;
  imei: string | null;
  supplier: string | null;
  product_note: string | null;
  selected_stock: string | null;
  vat_type: string | null;
  total_stock: number | null;
  raw_purchase_price: number | null;
  stock_total: number | null;
  category_brand: string | null;
  category_model: string | null;
  category_type: string | null;
  parent_id: string | null;
  is_parent: boolean | null;
  serial_number: string | null;
  battery_level: number | null;
  stock_id: string | null;
  warranty_sticker: string | null;
  battery_percentage: number | null;
  retail_price_ht: number | null;
  retail_margin: number | null;
  retail_price_ttc: number | null;
  pro_price_ht: number | null;
  pro_margin: number | null;
  pro_price_ttc: number | null;
  purchase_price: number | null;
  pro_margin_net: number | null;
  retail_margin_net: number | null;
  margin_percent: number | null;
  margin_value: number | null;
  pro_margin_percent: number | null;
  pro_margin_value: number | null;
  shared_stock_id: string | null;
  mirror_id: string | null;
  mirror_name: string | null;
  mirror_sku: string | null;
  mirror_stock: number | null;
  mirror_of: string | null;
  shared_quantity: number | null;
  product_type?: 'PAU' | 'PAM' | null;
  stocks: any;
  category?: {
    type: string;
    brand: string;
    model: string;
  } | null;
}
